= SchoolItbot
Телеграмм бот для автоматизации работы с документами участников https://itsolschool.ru[Школы IT-решений]


== Конфигурация

trello_api_key:: Публичный ключ из Trello. Получить можно по ссылке https://trello.com/app-key
trello_secret:: Секретный токен. Получается по той же ссылке, но ссылка на него находится в приложении про тестирование.
github_username:: Имя пользователя в GitHub для хранения там доков команд
github_password:: Пароль пользователя в GH
telegram_token:: Bot API token для телеграма. Получается у https://t.me/BotFather[@BotFather].
tg_id:: ID первого человека, который будет в команде организаторов автоматически.
Получить можно у https://t.me/userinfobot[@userinfobot]
tg_username:: Ник того же самого первого админа. **Без собачки в начале**
firstname:: Имя первого админа
lastname:: Фамилия первого админа

gdrive_secret:: Секретный токен для GDrive. После выполнения
https://habr.com/ru/post/328248/[инструкции из статьи на Хабре]
из файла `drive-secret.json` всё содержимое переписать в эту переменную

proxy:: Обычный https прокси URL. Погуглить можно по `https proxy for tg`

db_url:: URL для подключения к БД PostgreSQL

org_team_name:: Название команды организаторов
org_team_capacity:: Максимальное количество организаторов

docs:: *возможно* этапы и порядок подачи документов...

webhook_url:: URL хука, на котором должен жить бот.

== Неочевидные факты
Если в БД отсутствует команда с именем `org_team_name` из конфигурации, то она создаётся.

Если в БД отсутствует человек с `tg_id` из конфига, то он создаётся.

Чтобы зарегистрировать бота и его хуки надо перейти в браузере по адресу `<server-name.example.com>/sethook`