export const GDRIVE_SERVICE = 'GDRIVE_SERVICE',
    GDRIVE_PROVIDER = 'GDRIVE_PROVIDER',
    TRELLO_SERVICE = 'TRELLO_SERVICE',
    TRELLO_PROVIDER = 'TRELLO_PROVIDER',
    DB_SERVICE = 'DB_SERVICE',
    REDIS_SERVICE = 'REDIS_SERVICE',
    BOT_SERVICE = 'BOT_SERVICE';
