= Конфигурация проекта
:toc:


== Переменные окружения
TG_BOT_TOKEN::
Bot API token для телеграма. Получить можно у https://t.me/BotFather[@BotFather].

PORT::
Порт, на котором должен слушать webhook

WEBHOOK_URL::
_Опционально_.
- Если установлен, например `http://domain.com/path`, то зарегистрирует этот вебхук у телеграма
и запустит локальный http сервер на порту `PORT` с прослушкой на `/path`.
- Если не установлен, то будет использоваться Longpoll

GDRIVE_OAUTH2_SECRET::
OAuth2 секрет, который можно получить link:docs/connect_gdrive.adoc[по инструкции].

TRELLO_TOKEN_SECRET::
Пара `<api key>:<token>`. Api key можно https://trello.com/app-key[получить в devtools].
Token можно сгенерировать там же, ссылкой ниже. Если не установлено, то старается брать это значени из бд.

SENTRY_DSN::
DSN адрес из https://docs.sentry.io/error-reporting/quickstart/?platform=node#configure-the-sdk[документации к Sentry].

NODE_ENV::
В продакшене обязательно должно быть значение `production`. Во время разработки можно использовать `development`.

DATABASE_URL::
_Обязательно_, если `NODE_ENV=production`. URL к PostgreSQL.

REDIS_URL::
_Опционально_. URL к Redis. Если установлено, то все сессии хранятся там,
если не установлено, то в памяти процесса.

== Файл link:config/general.json[`config/general.json`]

gdrive.rootDirName::
Имя папки на GDrive, в которой будут хранится все файлы команд.

trello.boardId::
Id доски, где будет создана колонка "Spawn Teams". Можно получить вставив id из короткой ссылки на доску в метод
https://developers.trello.com/reference#boardsboardid-1[/boards/id].

[#milestones]
milestones::
Масств названий всех документов по порядку, которые должна предоставить команда.
__TODO убрать это в бд.__

allowedMIMEs::
https://ru.wikipedia.org/wiki/Список_MIME-типов[Все MIME] типы файлов, которые может сохранять бот.

fileMask::
Маска имени файла, при сохранении на GDrive.

.Переменные в fileMask
    milestoneNum:: Номер документа по порядку из <<milestones>>, начиная с 1
    milestoneTitle:: Название документа из <<milestones>>
    versionNumber:: Номер версии файла